FROM node:lts-alpine as build-stage

RUN mkdir /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json

RUN npm install
RUN npm run build

COPY . /app
CMD ["npm", "start"]

# FROM nginx:stable-alpine as production-stage
# RUN rm /etc/nginx/conf.d/default.conf
# COPY ./nginx/homepage.conf /etc/nginx/conf.d/homepage.conf

# COPY --from=build-stage ./homepage/dist /usr/share/nginx/html/homepage
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]