FROM node:lts-alpine as build-stage

RUN mkdir /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json

RUN npm install

COPY . /app
RUN npm run build

CMD ["npm", "start"]

FROM nginx:1.20.0-alpine
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

RUN ls
COPY --from=build-stage ./app/build /usr/share/nginx/html/app
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# FROM nginx:stable-alpine as production-stage
# RUN rm /etc/nginx/conf.d/default.conf
# COPY ./nginx/homepage.conf /etc/nginx/conf.d/homepage.conf

# COPY --from=build-stage ./homepage/dist /usr/share/nginx/html/homepage
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]