FROM adoptopenjdk/openjdk11:ubi AS builder
COPY gradlew .
COPY gradle gradle
COPY build.gradle
COPY settings.gradle
COPY src src
RUN chmod +x
RUN ./gradlew bootJar

FROM adoptopenjdk/openjdk11:ubi
COPY --from=builder build/libs/*.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java","-jar","/app.jar"]